# Generated by Django 2.1.7 on 2019-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logopath',
            field=models.TextField(),
        ),
    ]
